project:
  type: website

website:
  title: "My Datascience Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents: posts/**
    collapse-level: 3
    style: floating
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    highlight-style: breeze
    toc: true